services:

 postgres:
  image: postgres
  environment:
   POSTGRES_USER: postgres
   POSTGRES_DB: saas_db
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  ports:
   - "5432:5432"

 api:
  build: .
  ports:
   - "5000:5000"
  depends_on:
   - postgres
  env_file:
    - .env