export const AUDIT_ACTIONS = {
  // auth
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_TOKEN_REFRESH: 'AUTH_TOKEN_REFRESH',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_PASSWORD_RESET_REQUESTED: 'AUTH_PASSWORD_RESET_REQUESTED',
  AUTH_PASSWORD_RESET_COMPLETED: 'AUTH_PASSWORD_RESET_COMPLETED',

  // user

  USER_CREATED: 'USER_CREATED',
  USER_CREATE_FAILED: 'USER_CREATE_FAILED',

  USER_UPDATED: 'USER_UPDATED',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',

  USER_DELETED: 'USER_DELETED',
  USER_DELETE_FAILED: 'USER_DELETE_FAILED',

  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',

  // org

  ORG_CREATED: 'ORG_CREATED',
  ORG_CREATE_FAILED: 'ORG_CREATE_FAILED',

  ORG_UPDATED: 'ORG_UPDATED',
  ORG_UPDATE_FAILED: 'ORG_UPDATE_FAILED',

  ORG_DELETED: 'ORG_DELETED',
  ORG_DELETE_FAILED: 'ORG_DELETE_FAILED',

  ORG_SETTINGS_UPDATED: 'ORG_SETTINGS_UPDATED',

  // patient
  PATIENT_CREATED: 'PATIENT_CREATED',
  PATIENT_CREATE_FAILED: 'PATIENT_CREATE_FAILED',

  PATIENT_UPDATED: 'PATIENT_UPDATED',
  PATIENT_UPDATE_FAILED: 'PATIENT_UPDATE_FAILED',

  PATIENT_DELETED: 'PATIENT_DELETED',
  PATIENT_DELETE_FAILED: 'PATIENT_DELETE_FAILED',

  PATIENT_RECORD_ACCESSED: 'PATIENT_RECORD_ACCESSED',
  PATIENT_MEDICAL_DATA_UPDATED: 'PATIENT_MEDICAL_DATA_UPDATED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
